--Creating Tables--
DROP TABLE CHARITY_EVENT CASCADE CONSTRAINTS;
CREATE TABLE CHARITY_EVENT (
        EVENT_ID NUMBER NOT NULL, 
        EVENT_NAME VARCHAR2(200) NOT NULL,
        EVENT_DESCRIPTION VARCHAR2(1000), 
        EVENT_START_DATE TIMESTAMP NOT NULL, 
        EVENT_END_DATE TIMESTAMP NOT NULL, 
        EVENT_GOAL_AMOUNT NUMBER NOT NULL,
        EVENT_ORGANIZATION_ID NUMBER NOT NULL, 
        CONSTRAINT CHARITY_EVENT_PK PRIMARY KEY (EVENT_ID)
);

DROP TABLE CHARITY_ORGANIZATION CASCADE CONSTRAINTS;
CREATE TABLE CHARITY_ORGANIZATION (
        ORGANIZATION_ID NUMBER NOT NULL, 
        ORGANIZATION_NAME VARCHAR2(100) NOT NULL,
        ORGANIZATION_MANAGER_ID NUMBER NOT NULL,
        ORGANIZATION_BANK_ID NUMBER NOT NULL, 
        ORGANIZATION_TYPE_ID NUMBER NOT NULL, 
        CONSTRAINT CHARITY_ORGANIZATION_PK PRIMARY KEY (ORGANIZATION_ID)
);

DROP TABLE CHARITY_DONATION CASCADE CONSTRAINTS;
CREATE TABLE CHARITY_DONATION (
        DONATION_ID NUMBER NOT NULL, 
        DONATION_RECEIVER_ID NUMBER NOT NULL,
        DONATION_DONATOR_ID NUMBER NOT NULL, 
        DONATION_TRANSACTION_DATE TIMESTAMP NOT NULL,
        DONATION_AMOUNT NUMBER NOT NULL, 
        CONSTRAINT CHARITY_DONATION_PK PRIMARY KEY (DONATION_ID)
);

DROP TABLE CHARITY_USER CASCADE CONSTRAINTS;
CREATE TABLE CHARITY_USER (
        USER_ID NUMBER NOT NULL, 
        USER_FIRST_NAME VARCHAR2(100) NOT NULL, 
        USER_LAST_NAME VARCHAR2(100) NOT NULL, 
        USER_USERNAME VARCHAR2(50) NOT NULL UNIQUE, 
        USER_PASSWORD VARCHAR2(80) NOT NULL, 
        USER_EMAIL VARCHAR2(250) NOT NULL UNIQUE, 
        USER_ROLE_ID NUMBER NOT NULL, 
        USER_BANK_ID NUMBER NOT NULL, 
        CONSTRAINT CHARITY_USER_PK PRIMARY KEY (USER_ID)
);

DROP TABLE CHARITY_USER_ROLE CASCADE CONSTRAINTS;
CREATE TABLE CHARITY_USER_ROLE (
        USER_ROLE_ID NUMBER NOT NULL, 
        USER_ROLE_NAME VARCHAR2(20) NOT NULL, 
        CONSTRAINT CHARITY_USER_ROLE_PK PRIMARY KEY (USER_ROLE_ID)
);

DROP TABLE CHARITY_BANK CASCADE CONSTRAINTS;
CREATE TABLE CHARITY_BANK (
        BANK_ID NUMBER NOT NULL, 
        BANK_ACCOUNT_NUMBER NUMBER NOT NULL,
        BANK_ACCOUNT_ROUTING_NUMBER NUMBER NOT NULL,
        BANK_ACCOUNT_BALANCE NUMBER NOT NULL,
        CONSTRAINT CHARITY_BANK_PK PRIMARY KEY (BANK_ID)
);

DROP TABLE CHARITY_ORGANIZATION_TYPE CASCADE CONSTRAINTS;
CREATE TABLE CHARITY_ORGANIZATION_TYPE (
        ORGANIZATION_TYPE_ID NUMBER NOT NULL, 
        ORGANIZATION_NAME NUMBER NOT NULL,
        CONSTRAINT CHARITY_ORGANIZATION_TYPE_PK PRIMARY KEY (ORGANIZATION_TYPE_ID)
);



--Adding Foreign key constraints--
ALTER TABLE CHARITY_ORGANIZATION ADD CONSTRAINT FK_CH_ORGANIZATION_MANAGER_ID
    FOREIGN KEY (ORGANIZATION_MANAGER_ID) REFERENCES CHARITY_USER (USER_ID)  ;
    
ALTER TABLE CHARITY_ORGANIZATION ADD CONSTRAINT FK_CH_ORGANIZATION_BANK_ID
    FOREIGN KEY (ORGANIZATION_BANK_ID) REFERENCES CHARITY_BANK (BANK_ID)  ;
    
ALTER TABLE CHARITY_ORGANIZATION ADD CONSTRAINT FK_CH_ORGANIZATION_TYPE_ID
    FOREIGN KEY (ORGANIZATION_TYPE_ID) REFERENCES CHARITY_ORGANIZATION_TYPE (ORGANIZATION_TYPE_ID )  ;
    

    
ALTER TABLE CHARITY_USER ADD CONSTRAINT FK_CH_CHARITY_USER_ROLE_ID
    FOREIGN KEY (USER_ROLE_ID) REFERENCES CHARITY_USER_ROLE (USER_ROLE_ID)  ;
    
ALTER TABLE CHARITY_USER ADD CONSTRAINT FK_CH_CHARITY_USER_BANK_ID
    FOREIGN KEY (USER_BANK_ID) REFERENCES CHARITY_BANK (BANK_ID)  ;
    


ALTER TABLE CHARITY_EVENT ADD CONSTRAINT FK_CH_EVENT_ORGANIZATION_ID
    FOREIGN KEY (EVENT_ORGANIZATION_ID) REFERENCES CHARITY_ORGANIZATION (ORGANIZATION_ID);


    
ALTER TABLE CHARITY_DONATION ADD CONSTRAINT FK_CH_DONATION_RECEIVER_ID
    FOREIGN KEY (DONATION_RECEIVER_ID) REFERENCES CHARITY_EVENT (EVENT_ID)  ;
    
ALTER TABLE CHARITY_DONATION ADD CONSTRAINT FK_CH_DONATION_DONATOR_ID
    FOREIGN KEY (DONATION_DONATOR_ID) REFERENCES CHARITY_USER (USER_ID)  ;
  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    